version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: monitoring_prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: always
    ports:
      - "9100:9100"

  loki:
    image: grafana/loki:2.9.0
    container_name: monitoring_loki
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: monitoring_promtail
    restart: always
    volumes:
      - /var/log:/var/log
      - ./logs-auth.txt:/logs/logs-auth.txt
      - ./logs-booking.txt:/logs/logs-booking.txt
      - ./logs-payment.txt:/logs/logs-payment.txt
      - ./logs-reputation.txt:/logs/logs-reputation.txt
      - ./logs-ai.txt:/logs/logs-ai.txt
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: always
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki

volumes:
  prometheus_data:
  grafana_data:
